### ISSUE TITLE
自动生成的 mapper.xml 中 resultMap 的 jdbcType 需要转换

### ISSUE THREAD

**Issue by mgzu** [wuyouzhuguli/FEBS-Shiro#104]
### 问题描述
表结构
```
CREATE TABLE `t_site` (
  `SITE_ID` int(4) NOT NULL AUTO_INCREMENT COMMENT '站点编号',
  `SITE_NAME` varchar(100) NOT NULL COMMENT '站点名称',
  `SITE_PATH` varchar(100) NOT NULL COMMENT '站点简称',
  `KEYWORDS` varchar(100) DEFAULT NULL COMMENT '关键字',
  `DOMAIN_NAME` varchar(100) DEFAULT NULL COMMENT '域名',
  `ACCESS_PROTOCOL` varchar(10) DEFAULT NULL COMMENT '访问协议',
  `ACCESS_PATH` varchar(100) DEFAULT NULL COMMENT '访问地址',
  `SORT` char(3) DEFAULT NULL COMMENT '排序',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `MODIFY_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  `STATUS` char(1) DEFAULT NULL COMMENT '0、删除 1、正常',
  `REMARK` varchar(64) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`SITE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='站点管理';
```
实际生成的 mapper.xml（启动会报错）
```
    <resultMap id="site" type="cc.mrbird.febs.official.entity.Site">
        <id column="SITE_ID" jdbcType="int" property="siteId"/>
        <result column="SITE_NAME" jdbcType="varchar" property="siteName"/>
        <result column="SITE_PATH" jdbcType="varchar" property="sitePath"/>
        <result column="KEYWORDS" jdbcType="varchar" property="keywords"/>
        <result column="DOMAIN_NAME" jdbcType="varchar" property="domainName"/>
        <result column="ACCESS_PROTOCOL" jdbcType="varchar" property="accessProtocol"/>
        <result column="ACCESS_PATH" jdbcType="varchar" property="accessPath"/>
        <result column="SORT" jdbcType="char" property="sort"/>
        <result column="CREATE_TIME" jdbcType="datetime" property="createTime"/>
        <result column="MODIFY_TIME" jdbcType="datetime" property="modifyTime"/>
        <result column="STATUS" jdbcType="char" property="status"/>
        <result column="REMARK" jdbcType="varchar" property="remark"/>
    </resultMap>
```
期望生成的 mapper.xml
```
    <resultMap id="site" type="cc.mrbird.febs.official.entity.Site">
        <id column="SITE_ID" jdbcType="INTEGER" property="siteId"/>
        <result column="SITE_NAME" jdbcType="VARCHAR" property="siteName"/>
        <result column="SITE_PATH" jdbcType="VARCHAR" property="sitePath"/>
        <result column="KEYWORDS" jdbcType="VARCHAR" property="keywords"/>
        <result column="DOMAIN_NAME" jdbcType="VARCHAR" property="domainName"/>
        <result column="ACCESS_PROTOCOL" jdbcType="VARCHAR" property="accessProtocol"/>
        <result column="ACCESS_PATH" jdbcType="VARCHAR" property="accessPath"/>
        <result column="SORT" jdbcType="CHAR" property="sort"/>
        <result column="CREATE_TIME" jdbcType="TIMESTAMP" property="createTime"/>
        <result column="MODIFY_TIME" jdbcType="TIMESTAMP" property="modifyTime"/>
        <result column="STATUS" jdbcType="CHAR" property="status"/>
        <result column="REMARK" jdbcType="VARCHAR" property="remark"/>
    </resultMap>
```

**Comment by wuyouzhuguli** [comment]
todo

**Comment by hfld** [comment]
修改GeneratorMapper.xml中的getColumns为如下代码即可：

    <select id="getColumns" resultType="column">
        SELECT
        COLUMN_NAME name,
        CASE
            COLUMN_key
        WHEN 'PRI' THEN
                1 ELSE 0
        END isKey,
        CASE DATA_TYPE
        WHEN 'char' THEN 'CHAR'
        WHEN 'varchar' THEN 'VARCHAR'
        WHEN 'bigint' THEN 'BIGINT'
        WHEN 'int' THEN 'INTEGER'
        WHEN 'tinyint' THEN 'TINYINT'
        WHEN 'smallint' THEN 'SMALLINT'
        WHEN 'mediumint' THEN 'MEDIUMINT'
        WHEN 'double' THEN 'DOUBLE'
        WHEN 'float' THEN 'FLOAT'
        WHEN 'decimal' THEN 'DECIMAL'
        WHEN 'numeric' THEN 'NUMERIC'
        WHEN 'bit' THEN 'BOOLEAN'
        WHEN 'real' THEN 'REAL'
        WHEN 'date' THEN 'DATE'
        WHEN 'time' THEN 'TIME'
        WHEN 'datetime' THEN 'TIMESTAMP'
        WHEN 'timestamp' THEN 'TIMESTAMP'
        WHEN 'blob' THEN 'BLOB'
        WHEN 'tinyblob' THEN 'BLOB'
        WHEN 'mediumblob' THEN 'BLOB'
        WHEN 'longblob' THEN 'BLOB'
        WHEN 'text' THEN 'LONGVARCHAR'
        WHEN 'tinytext' THEN 'LONGVARCHAR'
        WHEN 'mediumtext' THEN 'LONGVARCHAR'
        WHEN 'longtext' THEN 'LONGVARCHAR'
        END type,
        COLUMN_COMMENT remark
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = #{schemaName} AND TABLE_NAME = #{tableName}
    </select>

**Comment by wuyouzhuguli** [comment]
@hfld
感谢！

**Comment by yejianmail** [comment]
不能按上面的修改,按上面的修改了,生成的entity类,有的属性会丢失

**Comment by hfld** [comment]
> 不能按上面的修改,按上面的修改了,生成的entity类,有的属性会丢失
把上面的转换后类型，增加到entity.ftl就行了：
-----------resources\generator\templates\entity.ftl----------------
package ${basePackage}.${entityPackage};

<#if hasDate = true>
import java.util.Date;
</#if>
<#if hasBigDecimal = true>
import java.math.BigDecimal;
</#if>

import lombok.Data;
import com.baomidou.mybatisplus.annotation.*;
import com.wuwenze.poi.annotation.Excel;
import com.wuwenze.poi.annotation.ExcelField;

/**
 * ${tableComment} Entity
 *
 * @author ${author}
 * @date ${date}
 */
@Data
@TableName("${tableName}")
public class ${className} {

    <#if columns??>
        <#list columns as column>
    /**
     * ${column.remark}
     */
    <#if column.isKey = true>
    @TableId(value = "${column.name}", type = IdType.AUTO)   
    <#else>
    @TableField("${column.name}")
    </#if>
    <#if (column.type = 'varchar' || column.type = 'text' || column.type = 'uniqueidentifier'
        || column.type = 'varchar2' || column.type = 'nvarchar' || column.type = 'char' || column.type = 'VARCHAR2'
        || column.type = 'VARCHAR'|| column.type = 'CLOB' || column.type = 'CHAR' || column.type = 'LONGVARCHAR')>
    @ExcelField(value = "${column.remark}")
    private String ${column.field?uncap_first};

    </#if>
    <#if column.type = 'timestamp' || column.type = 'date' || column.type = 'datetime' || column.type = 'TIMESTAMP' || column.type = 'DATE' || column.type = 'TIME'>
    private Date ${column.field?uncap_first};

    </#if>
    <#if column.type = 'int' || column.type = 'smallint' || column.type = 'mediumint' || column.type = 'INTEGER' || column.type = 'SMALLINT' || column.type = 'MEDIUMINT'>
    private Integer ${column.field?uncap_first};

    </#if>
    <#if column.type = 'bigint' || column.type = 'BIGINT'>
    private Long ${column.field?uncap_first};

    </#if>
    <#if column.type = 'double' || column.type = 'DOUBLE'>
    private Double ${column.field?uncap_first};

    </#if>
    <#if column.type = 'tinyint' || column.type = 'TINYINT' >
    private Byte ${column.field?uncap_first};

    </#if>
    <#if column.type = 'decimal' || column.type = 'numeric' || column.type = 'DECIMAL' || column.type = 'NUMERIC'>
    private BigDecimal ${column.field?uncap_first};

    </#if>
        </#list>
    </#if>   
}

**Comment by wuyouzhuguli** [comment]
已去掉resultMap
