### ISSUE TITLE
session过期为何定位到500错误页面

### ISSUE THREAD

**Issue by hfld** [wuyouzhuguli/FEBS-Shiro#105]
### 问题描述
主页面长时间不操作，session过期后再操作，为何定位到500错误页面？为何不直接提醒session过期，重新登录。500是内部服务器错误，会让用户以为是服务器问题或代码问题 。

### 复现步骤
主页面长时间不操作，session过期后再操作，会重定向到500错误页面。

### 相关截图
![TIM截图20190924150013](https://user-images.githubusercontent.com/30859506/65490497-d8ed1480-dedf-11e9-9fa7-aaeb3f465579.png)

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
感谢指出，已修复
