### ISSUE TITLE
关于v2.0分支的数据库可移植性

### ISSUE THREAD

**Issue by pangPython** [wuyouzhuguli/FEBS-Shiro#107]
### 问题描述
2.0版本中 多个mybatis的mapper文件SQL中使用了MySQL特有函数如group_concat，如果想把数据库实现替换成sqlserver，需要多处改动mapper。是否考虑增强2.0分支的数据库可移植性？thank you！

### 相关截图
![image](https://user-images.githubusercontent.com/12680677/65850735-9796b200-e382-11e9-9502-096ffd8943aa.png)

**Comment by lifespy** [comment]
我认为如果考虑到数据库移植性的话，还不如搞成jpa

**Comment by lerry903** [comment]
用mybatis想换数据库不改程序不切实际

**Comment by pangPython** [comment]
> 我认为如果考虑到数据库移植性的话，还不如搞成jpa

是的

**Comment by pangPython** [comment]
> 用mybatis想换数据库不改程序不切实际

还是改SQL吧^_^
