### ISSUE TITLE
代码生成怎么生成前端页面代码

### ISSUE THREAD

**Issue by yangzhenlong** [wuyouzhuguli/FEBS-Shiro#108]
### 问题描述
目前代码生成只有后台代码，没有前端代码？怎么能生成前端代码，或者目前只能自己写前端代码吗？

**Comment by listen-lee** [comment]
有前端页面，路径：
FEBS-Shiro/src/main/resources/templates/

**Comment by listen-lee** [comment]
> ### 问题描述
> 目前代码生成只有后台代码，没有前端代码？怎么能生成前端代码，或者目前只能自己写前端代码吗？

有前端页面，路径：
FEBS-Shiro/src/main/resources/templates/

**Comment by yangzhenlong** [comment]
> > ### 问题描述
> > 目前代码生成只有后台代码，没有前端代码？怎么能生成前端代码，或者目前只能自己写前端代码吗？
> 
> 有前端页面，路径：
> FEBS-Shiro/src/main/resources/templates/

新功能以 /templates/ 目录下的代码为示例代码来开发吗？

**Comment by wuyouzhuguli** [comment]
没有定义前端页面模板。新功能照着现有的页面开发

**Comment by yangzhenlong** [comment]
> 没有定义前端页面模板。新功能照着现有的页面开发

好的明白了，谢谢！
