### ISSUE TITLE
能详细告知下 控制台的sql语句是怎么获取的么？ 谢谢

### ISSUE THREAD

**Issue by AiMing317** [wuyouzhuguli/FEBS-Shiro#110]
### 问题描述
简单描述下遇到的问题

### 复现步骤
简单描述下问题复现的步骤

### 相关截图
提供相关截图，以协助问题分析

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
https://github.com/p6spy/p6spy
