### ISSUE TITLE
JobMapper.xml返回结果集错误

### ISSUE THREAD

**Issue by wangjw0811** [wuyouzhuguli/FEBS-Shiro#111]
### 问题描述
简单描述下遇到的问题

### 复现步骤
简单描述下问题复现的步骤

### 相关截图
提供相关截图，以协助问题分析

> issue模板，by MrBird.

**Comment by naiveZhou** [comment]
问题描述

- 根据最新版本的框架，启动报错
![image](https://user-images.githubusercontent.com/18117945/67613152-d894b180-f7dc-11e9-9918-d30e00e84147.png)

- 只要启动就报错，请问大佬，这个现象最近才发生的，请教如何解决，谢谢

**Comment by wuyouzhuguli** [comment]
检查mapper接口和xml文件内容是否匹配。

**Comment by naiveZhou** [comment]
感谢回复，这个问题检查一天了，文件名称都对的，网上的其他说法：@Service 和@Transactional都试过了，没有效果，注释了这几个类，可以运行
还有一个问题，就是登录，验证码部分写法会因为写法问题造成验证失败
图一，验证码输入无问题
![image](https://user-images.githubusercontent.com/18117945/67615548-6e8e0380-f800-11e9-9bec-0d6edd67eda9.png)
图二，使用== 判断是false
![image](https://user-images.githubusercontent.com/18117945/67615563-85345a80-f800-11e9-93f1-59a6a04e6ba4.png)
图三.现象
![image](https://user-images.githubusercontent.com/18117945/67615571-9aa98480-f800-11e9-8c2f-13ad8e6c7a58.png)
是StringUtils类的写法存在问题了？
![image](https://user-images.githubusercontent.com/18117945/67615581-b44acc00-f800-11e9-969f-46df9c0cf375.png)

**Comment by naiveZhou** [comment]
此类报错，还有和配置文件相关的原因，已查明是application.yml 配置文件中丢失mybatis-plus: 的配置，谢谢指正
