### ISSUE TITLE
日志配置文件有两个root元素

### ISSUE THREAD

**Issue by jht385** [wuyouzhuguli/FEBS-Shiro#112]
### 问题描述
我就想p6spy只是又输出一遍，但是跑你的应用怎么能做到压制mybatis日志只输出p6spy
猜了半天，看到你的logback-spring.xml有两个root元素
实际跑起来他控制台打印的也按照level="info"的来了
之前也没看过这种写法，看看是不是写错了，还是说老哥你研究过这么用

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
配置多个root可以指定不同的打印级别
