### ISSUE TITLE
UserServiceImpl类中的updateUser(User user)方法BUG

### ISSUE THREAD

**Issue by hfld** [wuyouzhuguli/FEBS-Shiro#113]
### 问题描述
UserServiceImpl类中的updateUser(User user)方法中：
user.setUsername(null);
后面又有条件判断”当前用户“的用户名与”所修改用户“的用户名是否相同，决定是否执行清空权限缓存：
User currentUser = GbapUtil.getCurrentUser();
        if (StringUtils.equalsIgnoreCase(currentUser.getUsername(), user.getUsername())) {
            shiroRealm.clearCache();
        }
结果是永远不相同，因为user.setUsername(null);
后果：在修改本人的用户权限时，权限缓存不被清空，而使权限设置不能立即生效。

### 复现步骤
同问题描述。

### 相关截图
![UserServiceImpl](https://user-images.githubusercontent.com/30859506/67617732-ccc6e080-f818-11e9-800a-3fde4c12d585.jpg)

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
感谢指出，已经修复。
