### ISSUE TITLE
sql脚本错误

### ISSUE THREAD

**Issue by Cra-zy** [wuyouzhuguli/FEBS-Shiro#115]
### sql语句错误
执行sql脚本时提示语法错误

### 复现步骤
直接执行作者仓库中的sql脚本（febs_base.sql）会报语法错误，修改datetime(0) 为 datetime

**Comment by mgzu** [comment]
这个要看你使用的 mysql 版本，项目用的是 5.7，用其它的版本肯能会存在问题。

**Comment by Cra-zy** [comment]
> 这个要看你使用的 mysql 版本，项目用的是 5.7，用其它的版本肯能会存在问题。

哈哈哈，忽略了这个因素，感谢提醒
