### ISSUE TITLE
request中获取外网ip,一直是同一个ip,没有变化

### ISSUE THREAD

**Issue by Silence-Shen** [wuyouzhuguli/FEBS-Shiro#118]
### 问题描述
程序运行后,用不同的外网ip去登录访问,在系统中显示的都是同一个ip地址

**Comment by Silence-Shen** [comment]
![image](https://user-images.githubusercontent.com/19200697/68763837-6503f880-0654-11ea-908f-7568b67f4c44.png)
这是用不同ip的设备登录的

**Comment by Silence-Shen** [comment]
IPUtil.getIpAddr
这个只能取到内网地址吗?

**Comment by wuyouzhuguli** [comment]
项目部署在公网的话，是可以获取到的。

**Comment by Silence-Shen** [comment]
> 项目部署在公网的话，是可以获取到的。
获取的IP不准确,确实和内网的配置方式有关,
本地试下来,映射到外网,可以正常获取到公网ip.
谢谢,有思路去解决这个问题了.
