### ISSUE TITLE
建议把项目中用到的layui扩展formSelects 4.x 升级为xmSelect

### ISSUE THREAD

**Issue by pangPython** [wuyouzhuguli/FEBS-Shiro#122]
### 问题描述
https://fly.layui.com/extend/formSelects/
formSelects停止维护, 已迁移至全新版本 https://maplemei.gitee.io/xm-select/#/component/install
https://fly.layui.com/extend/xmSelect/
https://gitee.com/maplemei/xm-select

### 相关截图
![image](https://user-images.githubusercontent.com/12680677/70029036-1dccb000-15e1-11ea-97d1-965ced435e90.png)

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
好的
