### ISSUE TITLE
token过期时间问题

### ISSUE THREAD

**Issue by dubujianghu** [wuyouzhuguli/FEBS-Shiro#123]
### 问题描述
用户正在操作，token过期，强制要重新登录。体验不好，希望在用户操作时无感刷新token过期时间
### 复现步骤
简单描述下问题复现的步骤

### 相关截图
提供相关截图，以协助问题分析

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
基于session的单体应用，怎么刷新令牌？

**Comment by dubujianghu** [comment]
> 基于session的单体应用，怎么刷新令牌？

不好意思我问题提错项目了，我本来说的是你那个前后端分离的那个项目(FEBS-Vue)的后端

**Comment by wuyouzhuguli** [comment]
那个项目不维护了，FEBS-Cloud有这个功能。

**Comment by dubujianghu** [comment]
好的，谢谢！
