### ISSUE TITLE
为什么菜单管理中上级ID都设置成不可编辑的呢？

### ISSUE THREAD

**Issue by Gumball82** [wuyouzhuguli/FEBS-Shiro#127]
### 问题描述
菜单管理中，不管是新增还是修改都无法编辑上级id的输入框，查看属性发现它被设置成readOnly，为什么这么设计啊？

### 复现步骤
菜单管理，新增，修改菜单选项

### 相关截图
![image](https://user-images.githubusercontent.com/55353535/70305955-9aa99500-1840-11ea-86b6-2c80ab071d79.png)

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
因为设定为不能修改父级，如果不设置为只读，你通过修改父级ID也很不直观。

最好的做法也是最普遍的做法就是这里改为树形下来框，但无奈的是没找到好用的基于layui的树形下拉选插件。
