### ISSUE TITLE
样式兼容：角色管理中角色名称字体展示换行

### ISSUE THREAD

**Issue by it-noob** [wuyouzhuguli/FEBS-Shiro#130]
### 问题描述
简单描述下遇到的问题

### 复现步骤
Safari 13.0.3 展示页面有问题

### 相关截图
![image](https://user-images.githubusercontent.com/12043442/70608433-19387500-1c3b-11ea-823a-0dbf7cf6d3f7.png)

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
这个不同分辨率下显示效果有细微差距，不好控制。

**Comment by it-noob** [comment]
好吧，Chrome 没有这个问题，另外，我测试了多个外接显示器，貌似就是 Safari 有问题，后续可以关注一下
