### ISSUE TITLE
查询用户有个小BUG

### ISSUE THREAD

**Issue by victor-jml** [wuyouzhuguli/FEBS-Shiro#132]
### 问题描述
在系统管理中的用户管理中,根据创建时间查询用户后,清除创建时间再次查询所有用户不能实现,会一直出现上一次通过创建时间查询用户的结果

### 复现步骤
在用户管理中通过创建时间条件查询用户,然后清除创建时间想要查询所有用户,查询结果依旧是上一次通过创建时间查询的

**Comment by wuyouzhuguli** [comment]
// TODO

**Comment by wuyouzhuguli** [comment]
已修复。
