### ISSUE TITLE
时间选择器失效

### ISSUE THREAD

**Issue by harryer** [wuyouzhuguli/FEBS-Shiro#133]
### 问题描述
打开第二个或第三个带有时间选择器的选项卡后，之前选项卡中的时间选择器失效

### 复现步骤
1、打开用户管理，选择时间，可以选择
2、打开系统日志，选择时间，可以选择
3、点击用户管理选项卡，选择时间，没反应，时间选择器不出现

### 相关截图
![image](https://user-images.githubusercontent.com/9066985/71092220-cbdf7900-21e1-11ea-8a29-31d51005b4b0.png)
![image](https://user-images.githubusercontent.com/9066985/71092258-df8adf80-21e1-11ea-82b9-b21d1138515c.png)
![image](https://user-images.githubusercontent.com/9066985/71092292-e9acde00-21e1-11ea-9b1b-6cf6d5df25c3.png)

> issue模板，by MrBird.

**Comment by mgzu** [comment]
这两个时间选择器应该都是用 id 初始化的，当另一个时间选择器器初始化后，上一个时间选择器会失效

**Comment by wuyouzhuguli** [comment]
已修复。
