### ISSUE TITLE
有潜在的csrf攻击和权限越级

### ISSUE THREAD

**Issue by Mhunter132** [wuyouzhuguli/FEBS-Shiro#134]
### 问题描述
简单描述下遇到的问题
1.csrf攻击
2. 低级用户能通过日志拿到高级用户的账号密码
### 复现步骤
简单描述下问题复现的步骤
信安那头发的报告
### 相关截图
提供相关截图，以协助问题分析

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
CSRF攻击自己完善；关于第2点可以具体说明么？

**Comment by Mhunter132** [comment]
低级用户能通过日志接口查看日志找到高级用户的账号和密码。我们直接就是把账号密码移除了

**Comment by wuyouzhuguli** [comment]
没明白，具体怎么操作？比如scott如何看到mrbird的密码

**Comment by wuyouzhuguli** [comment]
// 没有后续反馈，故关闭
