### ISSUE TITLE
数据库字符集编码暂不支持emoji

### ISSUE THREAD

**Issue by Matthew-Han** [wuyouzhuguli/FEBS-Shiro#136]
### 问题描述
在本系统中的大量可键入字符串的文本框里，一旦出现emoji表情，便会向上转型抛出异常，实际可能已经执行了相关SQL语句。

- 数据库版本：Mysql 5.7
- 数据库编码：utf8m4，部分字段编码依然是utf8

### 相关截图
![421578551113_ pic_hd](https://user-images.githubusercontent.com/22296600/72043446-22753a00-32ec-11ea-8b75-2b7f1a24a16a.jpg)
<img width="1439" alt="Xnip2020-01-09_14-29-00" src="https://user-images.githubusercontent.com/22296600/72043555-754ef180-32ec-11ea-8ad4-4caae863066d.png">

> issue模板，by MrBird.

**Comment by mgzu** [comment]
将需要存 emoji 的字段编码改为 utf8mb4 即可

**Comment by Matthew-Han** [comment]
> 将需要存 emoji 的字段编码改为 utf8mb4 即可

@mgzu 对，我之前就提出来了，我只是通过issue告知下他需要更新

**Comment by mgzu** [comment]
@Matthew-Han 一般的情况，使用 utf8 编码已经够了，utfmb4 编码是需要储存复杂汉字或 emoji 这种需求才会使用，有精力可以提个 pull request。
