### ISSUE TITLE
修改数据源为oracle

### ISSUE THREAD

**Issue by wwj154** [wuyouzhuguli/FEBS-Shiro#165]
### 问题描述
可以修改连接oracle数据库吗

**Comment by wuyouzhuguli** [comment]
主要修改两个地方：
mybatis xml sql（MySQL Oracle SQL部分语法不同）；
insert插入时的主键策略（MySQL Oracle主键生成策略不通，具体可以参考mybatis plus文档）。

**Comment by wuyouzhuguli** [comment]
主要修改两个地方：
mybatis xml sql（MySQL Oracle SQL部分语法不同）；
insert插入时的主键策略（MySQL Oracle主键生成策略不通，具体可以参考mybatis plus文档）。
