### ISSUE TITLE
验证码不显示

### ISSUE THREAD

**Issue by 2334754668** [wuyouzhuguli/FEBS-Shiro#168]
请问，我在使用系统时出现以下问题：
### 问题描述
linux下部署出现验证码不显示问题。
提示错误 org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class java.util.LinkedHashMap] with preset Content-Type 'image/png'
windows下没有问题

### 相关截图
提供相关截图，以协助问题分析
![image](https://user-images.githubusercontent.com/37646969/77670023-95738000-6fc0-11ea-86b1-620fb6119d81.png)
![image](https://user-images.githubusercontent.com/37646969/77670154-c0f66a80-6fc0-11ea-87d6-8ab76d91d5d3.png)

谢谢！

**Comment by chenmingyu0903** [comment]
刚刚使用，也是图片不显示，请问你解决了吗

**Comment by wuyouzhuguli** [comment]
linux下的JDK什么版本

**Comment by chenmingyu0903** [comment]
> linux下的JDK什么版本

谢谢  解决了

**Comment by 2334754668** [comment]
JDK 是12.0.1
有几次打包后在linux可以显示，但大多数情况下还是不能显示验证码。
打包命令都一样，是打包的问题吗？

**Comment by wuyouzhuguli** [comment]
没在JDK12环境下试过，可以降回1.8试试。

**Comment by 2334754668** [comment]
试了还是不行呀，相同的JDK在window下就是好的。

**Comment by wuyouzhuguli** [comment]
演示环境也是linux+jdk8，没遇到你说的问题，你可以尝试使用docker的方式部署。

**Comment by mgzu** [comment]
@2334754668 @chenmingyu0903 这个最好说明 os 版本、jdk 信息才好排查问题，比如使用 openjdk 可能会因缺失字体导致出现问题

**Comment by 2334754668** [comment]
我用的debian10 +jdk12
但问题是，在同样的系统下，有时候打包jar后，是可以正常显示验证码的。
可是大多数情况下不行，用的打包命令mvn install都是相同的。
看错误提示，好像是linux下初始化bean顺序上出现了问题，可能验证码部分没有初始化。
怎样能强制让验证码初始化吗？

**Comment by ForeverLover** [comment]
这个问题解决了么。我系统centos7.5 jdk15.0.1也遇到了，本地win10和mac都没问题。可以学习下你的解决办法嘛

**Comment by mgzu** [comment]
@ForeverLover 发下 java -version 信息

**Comment by ForeverLover** [comment]
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

刚刚切换成了1.8，还是不行
之前的是
java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)



我的系统版本：
CentOS Linux release 7.5.1804 (Core)&nbsp;



下面是我的报错信息

。
麻烦你了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "febsteam/FEBS-Shiro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 下午4:17
收件人:&nbsp;"febsteam/FEBS-Shiro"<FEBS-Shiro@noreply.github.com&gt;;
抄送:&nbsp;"天外飞仙$#@1"<516885817@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [febsteam/FEBS-Shiro] 验证码不显示 (#168)





 
@ForeverLover 发下 java -version 信息

**Comment by ForeverLover** [comment]
![image](https://user-images.githubusercontent.com/6240611/100983688-9c598600-3584-11eb-998b-7d2b5e88cf54.png)
效果
![image](https://user-images.githubusercontent.com/6240611/100983765-bf843580-3584-11eb-9dcd-e0fc30e3ce6a.png)

**Comment by 2334754668** [comment]
> 这个问题解决了么。我系统centos7.5 jdk15.0.1也遇到了，本地win10和mac都没问题。可以学习下你的解决办法嘛

我用的是debian，安装libfontconfig后问题解决了，centos没有试过，你可以试试。

**Comment by ForeverLover** [comment]
谢谢大佬，真的是因为缺少字体引起的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ma Guang Zu"<notifications@github.com&gt;; 
发送时间: 2020年12月3日(星期四) 下午4:17
收件人: "febsteam/FEBS-Shiro"<FEBS-Shiro@noreply.github.com&gt;; 
抄送: "天外飞仙$#@1"<516885817@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [febsteam/FEBS-Shiro] 验证码不显示 (#168)





 
@ForeverLover 发下 java -version 信息

**Comment by foreveryang321** [comment]
由于使用了wf captcha组件来生成验证码，而依赖的基础镜像缺少相应字体，导致NPE错误。
解决方案：
方案一、使用frolvlad/alpine-java:jdk8-slim镜像
方案二、在Dockerfile中安装字体：RUN apk add --update ttf-dejavu fontconfig && rm -rf /var/cache/apk/*

**Comment by ForeverLover** [comment]
已解决，确实是缺少字体导致的。感谢🙏

**Comment by JAM2199562** [comment]
遇到了类似问题，CentOS 7用yum install xorg-x11-font-uti 解决的
