### ISSUE TITLE
findMenuList的查询ORDER BY了多余的column

### ISSUE THREAD

**Issue by wtune** [wuyouzhuguli/FEBS-Shiro#172]
### 问题描述
目前findMenuList的查询是这样的
```sql
SELECT 
  *
FROM 
  t_menu 
ORDER BY 
  MENU_ID ASC, 
  ORDER_NUM ASC
```
其中的ORDER BY子句，既然`MENU_ID`是唯一的，那么`ORDER BY MENU_ID ASC, ORDER_NUM ASC`和`ORDER BY MENU_ID`其实是完全一样的效果。但是写成前者的话，数据库不会使用索引而进行filesort，会比较慢。

### 可能的修改方法
见#171

**Comment by wuyouzhuguli** [comment]
感谢老哥指正！
