### ISSUE TITLE
laydate在多tab页下有的tab页不显示的问题

### ISSUE THREAD

**Issue by yejianmail** [wuyouzhuguli/FEBS-Shiro#175]
### 问题描述
简单描述下遇到的问题
开启多个tab页,最后一个tab页的的查询form的日期选择主键点击会弹出日期选择,前面的点击无反应

### 复现步骤
简单描述下问题复现的步骤
开启多个tab页,最后一个tab页的的查询form的日期选择主键点击会弹出日期选择,前面的点击无反应

### 相关截图
提供相关截图，以协助问题分析
查看页面代码发现多个tab页实际是在一个html下的多个layui卡片,因为日期选择控件的html标签id相同,所以只有最后一个控件会被laydate渲染,建议使用css选择器,选择form下的input标签来修复此问题

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
这个应该是你使用不当，不同页面的组件id不要相同。
