### ISSUE TITLE
febs.properties的验证码类型注释有误

### ISSUE THREAD

**Issue by hfld** [wuyouzhuguli/FEBS-Shiro#176]
### 问题描述
关于验证码类型的注释为：# 验证码类型：1. 纯字母；2. 纯数字；3. 数字+字母
经测试，发现有误。
问题原因：1和3颠倒了。
正确的注释应该是：# 验证码类型：1. 数字+字母；2. 纯数字；3. 纯字母

> issue模板，by MrBird.

**Comment by mgzu** [comment]
@hfld https://github.com/wuyouzhuguli/FEBS-Shiro/blob/085829bfdabdde63885d8c439352d8aa61638e6d/src/main/java/cc/mrbird/febs/common/properties/ValidateCodeProperties.java#L33  
这里写的是正确的，只是 properties 中写反了，建议提个 pr 修复这个描述问题
