### ISSUE TITLE
项目启动，定时任务初始化抛出 org.quartz.ObjectAlreadyExistsException异常

### ISSUE THREAD

**Issue by cleverdb** [wuyouzhuguli/FEBS-Shiro#177]
启动项目时候出现异常

定时任务配置的20秒一次
出现在问题在createScheduleJob 方法中scheduler.scheduleJob(jobDetail, trigger);

抛出异常
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'DEFAULT.TASK_1', because one already exists with this identification

**Comment by wuyouzhuguli** [comment]
项目导入后，如果改了包名，请重新导入febs_quartz.sql
