### ISSUE TITLE
大佬有时间在里面加一个刷新token吧

### ISSUE THREAD

**Issue by Tiny-zhongwen** [wuyouzhuguli/FEBS-Shiro#178]
大佬有时间在里面加一个刷新token吧

**Comment by mgzu** [comment]
@Tiny-zhongwen 这个项目前后端未分离，使用的是 session，如果你想保留更长时间的登录状态需要调整对应的过期时间

**Comment by Tiny-zhongwen** [comment]
我搞了好久没搞出来



---原始邮件---
发件人: "Ma Guang Zu"<notifications@github.com&gt;
发送时间: 2020年4月17日(周五) 晚上9:32
收件人: "wuyouzhuguli/FEBS-Shiro"<FEBS-Shiro@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"The_End"<zhangzhongwen_007@foxmail.com&gt;;
主题: Re: [wuyouzhuguli/FEBS-Shiro] 大佬有时间在里面加一个刷新token吧 (#178)




 
@Tiny-zhongwen 这个项目前后端未分离，使用的是 session，如果你想保留更长时间的登录状态需要调整对应的过期时间

**Comment by mgzu** [comment]
@Tiny-zhongwen https://github.com/wuyouzhuguli/FEBS-Shiro/blob/v2.0/src/main/resources/febs.properties#L4  
这个配置调大些还是有问题么

**Comment by Tiny-zhongwen** [comment]
不好意回复错项目了，是 https://github.com/wuyouzhuguli/FEBS-Vue 这个项目，这个您已经停止维护了，这里面的刷新token搞了好久没搞出来，能不能在里面加一个刷新token供小弟参考一下

**Comment by Tiny-zhongwen** [comment]
不好意回复错项目了，是 https://github.com/wuyouzhuguli/FEBS-Vue 这个项目，这个您已经停止维护了，我自己用这个项目，这里面的刷新token搞了好久没搞出来，能不能在里面加一个刷新token供小弟参考一下，谢啦

**Comment by ArcySun** [comment]
> 不好意回复错项目了，是 https://github.com/wuyouzhuguli/FEBS-Vue 这个项目，这个您已经停止维护了，我自己用这个项目，这里面的刷新token搞了好久没搞出来，能不能在里面加一个刷新token供小弟参考一下，谢啦

可以在登陆处新增一个刷新接口，重新签出一个token。
