### ISSUE TITLE
密码HASH方法不正确

### ISSUE THREAD

**Issue by code-n00b** [wuyouzhuguli/FEBS-Shiro#2]
使用MD5不足够安全 ，建议使用安全的算法比如PBKDF2，bcrypt，scrypt 。  
盐值使用固定盐值mrbird+用户名没有意义，建议使用随机盐，存储盐值到用户表。  
[如何安全的存储用户的密码](http://www.freebuf.com/articles/web/28527.html)

**Comment by wuyouzhuguli** [comment]
密码学没有深入研究过，感谢指出，推荐的文章很棒！
