### ISSUE TITLE
Controller里面 一个UserController.index 设置了权限，UserController.userList却没有权限

### ISSUE THREAD

**Issue by wangjia2016** [wuyouzhuguli/FEBS-Shiro#28]
![qq 20180918160611](https://user-images.githubusercontent.com/16084076/45673266-d03f6100-bb5c-11e8-9d2e-85dd7f044bc1.jpg)

一个相当于是导航页面，一个相当于是取数据的页面，
这两个都应该加权限控制吧？或者分开控制权限？

**Comment by wuyouzhuguli** [comment]
是的，应该都加`@RequiresPermissions("user:list")`。疏忽了，感谢。

**Comment by CrazyPeppa** [comment]
![image](https://user-images.githubusercontent.com/26081616/63495472-85f3fc00-c4f2-11e9-819f-433e8d285255.png)
问一下这两个list是否相同？

**Comment by dnflove962789** [comment]
看代码，好明显是吧




------------------ 原始邮件 ------------------
发件人: "CrazyPeppa"<notifications@github.com>;
发送时间: 2019年8月22日(星期四) 下午3:37
收件人: "wuyouzhuguli/FEBS-Shiro"<FEBS-Shiro@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [wuyouzhuguli/FEBS-Shiro] Controller里面 一个UserController.index 设置了权限，UserController.userList却没有权限 (#28)





 问一下这两个list是否相同？
