### ISSUE TITLE
建议作者弄一个开发分支一个稳定分支

### ISSUE THREAD

**Issue by cacacai** [wuyouzhuguli/FEBS-Shiro#30]
分支4505f9627af80accca47b29e462c7fc842e980ab验证码用不了。
但是早上我下载的是b881dfb2bad10d3e987485f9d0166f24ea1c08f2分支，早上我用的验证码还比较正常，下午我重新下载分支，然后验证码出问题，我还以为是我自己的问题。

**Comment by wuyouzhuguli** [comment]
现在验证码只有在直接访问/login的时候才会有问题吧
