### ISSUE TITLE
任意文件下载漏洞

### ISSUE THREAD

**Issue by 360CodeSafe** [wuyouzhuguli/FEBS-Shiro#40]
您好，我是奇虎360代码卫士团队的工作人员，在我们的开源项目检测中发现FEBS-Shiro存在任意文件下载漏洞，详细信息如下：
![default](https://user-images.githubusercontent.com/39950310/47981224-fa95af80-e105-11e8-90e8-ee27c34fa2a8.png)
在这个Controller中，没有对文件下载的路径和文件类型做任何过滤，导致恶意攻击者可以通过构造如下请求下载项目的敏感文件（如application.yml）
![default](https://user-images.githubusercontent.com/39950310/47981312-552f0b80-e106-11e8-8392-a698f73c64e7.png)
![default](https://user-images.githubusercontent.com/39950310/47981326-6415be00-e106-11e8-81d7-cf223f02abd4.png)
返回状态码为200。本来是想在http://111.230.157.133下通过../进行路径穿透演示下载application.yml文件的，但是由于该服务器上应该是配了waf的（也可能是其他原因）导致我的ip地址被加入到了黑名单，演示不了，您可以自行进行验证。

**Comment by wuyouzhuguli** [comment]
这应用是打成jar包部署的，配置文件application.yml位于jar文件里，所以通过您说的这种改变路径的方式来获取非法文件进行下载应该是行不通的。不过确实加上文件类型或者路径判断会更加安全！感谢您的指出，稍后会提交代码来修正。
