### ISSUE TITLE
README 中的树形模块图怎么做的

### ISSUE THREAD

**Issue by DraperHXY** [wuyouzhuguli/FEBS-Shiro#42]
请问一下树形的模块图是怎么做的
还有上面的 FEBS 四个字，学习一下，谢谢

**Comment by wuyouzhuguli** [comment]
1. windows下用tree命令生成；
2. 有挺多生成ASCII图的网站，推荐个http://www.network-science.de/ascii/。
这种问题可以加群讨论，不适合开issue哦。
