### ISSUE TITLE
linux下jar方式启动无法读取classpath:ip2region/ip2region.db

### ISSUE THREAD

**Issue by ouci** [wuyouzhuguli/FEBS-Shiro#44]
使用如下方式：先获取文件路径，将文件拷贝至新的临时路径下再使用classpath读取可解决。如下：
String dbPath = AddressUtils.class.getResource("/ip2region/ip2region.db").getPath();
            log.info("dbPath:{}", dbPath);
            File file = new File(dbPath);
            if (!file.exists()) {
                String tmpDir = System.getProperties().getProperty("java.io.tmpdir");
                dbPath = tmpDir + "ip.db";
                System.out.println(dbPath);
                file = new File(dbPath);
                FileUtils.copyInputStreamToFile(AddressUtils.class.getClassLoader().getResourceAsStream("classpath:ip2region/ip2region.db"), file);
            }

**Comment by wuyouzhuguli** [comment]
fixed
