### ISSUE TITLE
how to change the Material Design to other theme

### ISSUE THREAD

**Issue by 3313204840** [wuyouzhuguli/FEBS-Shiro#51]
my boss does not like the Material Design,I want to use other theme.i can not find the Material Design theme files,so i do not know how to change?

**Comment by wuyouzhuguli** [comment]
有以下解决方案：
1. 打老板一顿
2. 自己改CSS
3. 换一套前端UI框架
4. GitHub上找别的开源项目
5. 后期Vue版本不是MD设计

个人推荐 4 。
