### ISSUE TITLE
获取地址信息异常问题

### ISSUE THREAD

**Issue by BrunceWang** [wuyouzhuguli/FEBS-Shiro#59]
获取地址信息异常问题
![2019-03-06_103437](https://user-images.githubusercontent.com/37208212/53852064-945d6280-3ffb-11e9-9a46-c27cafe08e06.png)

**Comment by BrunceWang** [comment]
ip2region.db文件是乱码
![2019-03-06_103800](https://user-images.githubusercontent.com/37208212/53852168-fa49ea00-3ffb-11e9-8b2b-be93e516ed2c.png)

**Comment by wuyouzhuguli** [comment]
db文件不能直接打开。本地测试了没有你所说的问题

**Comment by BrunceWang** [comment]
问题解决了，是项目中文路径的问题
