### ISSUE TITLE
登录时验证码BUG

### ISSUE THREAD

**Issue by ZenMeQiMing** [wuyouzhuguli/FEBS-Shiro#60]
登录时输入正确的验证码，但是输入错误的用户名或者密码，此时点击登录会提示验证不通过，并且验证码没有发生变化，但是此时你输入正确的用户名密码，再点击登录，就会提示验证码错误

**Comment by wuyouzhuguli** [comment]
用户名或密码错误，验证码会刷新

**Comment by ZenMeQiMing** [comment]
> 用户名或密码错误，验证码会刷新

哦哦，可能你们GitHub上已经修复了这个BUG，我从码云下载的Oracle版本还是存在这个问题

**Comment by wuyouzhuguli** [comment]
> > 用户名或密码错误，验证码会刷新
> 
> 哦哦，可能你们GitHub上已经修复了这个BUG，我从码云下载的Oracle版本还是存在这个问题

嗯，你改改吧，难道不大

**Comment by ZenMeQiMing** [comment]
> > > 用户名或密码错误，验证码会刷新
> > 
> > 
> > 哦哦，可能你们GitHub上已经修复了这个BUG，我从码云下载的Oracle版本还是存在这个问题
> 
> 嗯，你改改吧，难道不大

嗯嗯，好的
