### ISSUE TITLE
数据库表不规范

### ISSUE THREAD

**Issue by wllfengshu** [wuyouzhuguli/FEBS-Shiro#65]
仔细看了下作者的数据库sql，觉得数据库设计的非常不规范，不论是字段名，还是表结构设计。
我觉得功能的实现不是最重要的，数据库设计的不合理，功能做的再好也只能是空中楼阁，后期维护非常麻烦。请作者先仔细设计数据库

**Comment by tang1998bjt** [comment]
你有什么更好的数据库设计?可以提出来

**Comment by wuyouzhuguli** [comment]
可以举例说明？具体哪个不规范，哪里会给维护带来麻烦？我不是DBA还请老哥赐教😭

**Comment by huluobo11** [comment]
我觉得群主选择项目开源在 github，有问题，github 全是英文不好用。项目起点就错了，功能做的再好也只能是空中楼阁，后期维护非常麻烦。请作者先把项目从github迁移出去，换成gitee吧。

**Comment by wx7614140** [comment]
我觉得您适合重新写一个开源的系统，看别的不顺眼就自己写个呗。

**Comment by wllfengshu** [comment]
不好意思啊，我的当时的语言有点过激了，实在抱歉。
先聊一下数据库表吧，本人对于数据库有点强迫症，还望理解。
第一张表QRTZ_JOB_DETAILS，大量的varchar，主键还是三个很大的varchar的联合主键；
还有第二张表...
我觉得吧，实现功能真的不用急，先设计好数据库，考虑数据库性能，优化好，哪怕是一个字段名，哪怕是一个字段类型，等等，这些细节都要设计好。不然到后面就是个坑。
其实我当时是想找一个做好的安全控制开源项目的，我会先看数据库设计，当时看到这样的表结构，的确内心很反感，语音用词不当，还望大家原谅。

**Comment by wuyouzhuguli** [comment]
QRTZ开头的表任务调度相关表，用于持久化调度任务。

项目里的任务调度使用的是quartz框架，这些表结构是quartz官方提供的，以2.3.0版本为例：
```
<!-- https://mvnrepository.com/artifact/org.quartz-scheduler/quartz -->
<dependency>
    <groupId>org.quartz-scheduler</groupId>
    <artifactId>quartz</artifactId>
    <version>2.3.0</version>
</dependency>
```
解压quartz.2.3.0.jar，在`org\quartz\impl\jdbcjobstore`路径下包含了各种关系型数据库表结构的初始化SQL。

可能表结构确实如你所说有不合理的地方，可以给[https://github.com/quartz-scheduler/quartz](https://github.com/quartz-scheduler/quartz)官方提issue哈。

**Comment by wllfengshu** [comment]
嗯，刚了解了下这个框架，是我的问题，没有弄清楚就随意发表评论，我道歉，不好意思。
