### ISSUE TITLE
分页不起作用

### ISSUE THREAD

**Issue by ethanCun** [wuyouzhuguli/FEBS-Shiro#67]
首先感恩提供学习资源，这个地方：

PageHelper.startPage(request.getPageNum(), request.getPageSize());

PageInfo<?> pageInfo = new PageInfo<>((List<?>) s.get());

s.get()这样写在startPage后面好像没用pageInfo.getList size不变化

不知道是不是我理解错了

**Comment by wuyouzhuguli** [comment]
没太理解你说的意思

无论从前端的结果还是SQL的打印来看，分页都是成功的

**Comment by ethanCun** [comment]
直观看上去的问题是这样：系统管理-》用户管理-》下边的每页显示几条 选择5条 或者 10条  第一页都是8条数据（本地总共只有8条数据）不是选择5的话 分成两页 第一页5条 第二页3条这样吗  
 代码上反映就是在selectByPageNumSize这个方法里面：
        PageHelper.startPage(request.getPageNum(), request.getPageSize());
      PageInfo<?> pageInfo = new PageInfo<>((List<?>) s.get());
    System.out.println("pageInfo = " + pageInfo.getTotal() + "  == " + pageInfo.getList().size());
这个 pageInfo.getList().size() 不会随着pageNum和pageSize的改变而改变

**Comment by wuyouzhuguli** [comment]
```java
protected Map<String, Object> selectByPageNumSize(QueryRequest request, Supplier<?> s) {
        PageHelper.startPage(request.getPageNum(), request.getPageSize());
        PageInfo<?> pageInfo = new PageInfo<>((List<?>) s.get());
        PageHelper.clearPage();
        System.out.println(request);
        System.out.println("total = " + pageInfo.getTotal() + " current size == " + pageInfo.getList().size());
        return getDataTable(pageInfo);
    }
```
测试结果：
```
QueryRequest{pageSize=10, pageNum=1}
total = 9 current size == 9

QueryRequest{pageSize=5, pageNum=1}
total = 9 current size == 5

QueryRequest{pageSize=5, pageNum=2}
total = 9 current size == 4
```

**Comment by ethanCun** [comment]
好的  多谢 我重新下一份
