### ISSUE TITLE
able 'febs_base.t_job' doesn't exist

### ISSUE THREAD

**Issue by boatt** [wuyouzhuguli/FEBS-Shiro#71]
### Cause: java.sql.SQLSyntaxErrorException: Table 'febs_base.t_job' doesn't exist
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'febs_base.t_job' doesn't exist

**Comment by wuyouzhuguli** [comment]
https://github.com/wuyouzhuguli/FEBS-Shiro/blob/v2.0/sql/febs_base.sql
