### ISSUE TITLE
账号密码怎么修改？ 

### ISSUE THREAD

**Issue by mark988** [wuyouzhuguli/FEBS-Shiro#74]
你好，超级管理员用户名 怎么修改？ 我不想使用mrbird 这个用户。

**Comment by wuyouzhuguli** [comment]
新建一个角色为超级管理员的账号即可

**Comment by mark988** [comment]
刚才下载你的代码，好像点问题。febs 项目中。AddressUtil类， FileUtils.copyInputStreamToFile 这行报错。似乎没有添加 apache  common io jar 造成的 。

**Comment by mark988** [comment]
请问后台前端，都是你一个人搞定的么？

**Comment by wuyouzhuguli** [comment]
pom里有common-io依赖

**Comment by wuyouzhuguli** [comment]
是的，角色项目不错的话，可以点个star哦

**Comment by mark988** [comment]
我启动报错，我手工添加一下，就不错了。

**Comment by mark988** [comment]
会点赞的。

**Comment by mark988** [comment]
能从数据库直接修改用户名么？

**Comment by wuyouzhuguli** [comment]
可以，密码也要相应修改

**Comment by mark988** [comment]
密码和用户名是关联的？ 单纯修改了用户名，也无法登陆系统对吧？

**Comment by wuyouzhuguli** [comment]
是，详见MD5Util

**Comment by mark988** [comment]
OK, 明白了。
