### ISSUE TITLE
权限系统设计

### ISSUE THREAD

**Issue by godchou** [wuyouzhuguli/FEBS-Shiro#76]
应该需要把权限设计的粒度更细一些，达到页面级别的元素，要不然只能当做学习用

**Comment by wuyouzhuguli** [comment]
按钮不是页面级别的元素么？

**Comment by godchou** [comment]
嗯，假如菜单下新增权限，每次上线前，需要先往数据库中新增对应数据吧

**Comment by wuyouzhuguli** [comment]
直接菜单管理添加就好了，不是很理解 "每次上线前，需要先往数据库中新增对应数据吧" 这句话
