### ISSUE TITLE
强烈请求作者大大加入druid监控和swagger

### ISSUE THREAD

**Issue by 635399797** [wuyouzhuguli/FEBS-Shiro#77]
如题

**Comment by wuyouzhuguli** [comment]
druid和swagger集成都很简单，可以自己改下。

**Comment by zhangyc** [comment]
头疼,集成了swagger但是一直什么都不显示..api是空的,我已经加了相关的注解和配置文件

**Comment by wuyouzhuguli** [comment]
说明你扫描路径不对------------------ 原始邮件 ------------------
发件人: "zhangyc"<notifications@github.com>
发送时间: 2019年8月23日(星期五) 下午3:45
收件人: "wuyouzhuguli/FEBS-Shiro"<FEBS-Shiro@noreply.github.com>;
抄送: "mrbird"<852252810@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [wuyouzhuguli/FEBS-Shiro] 强烈请求作者大大加入druid监控和swagger (#77)



头疼,集成了swagger但是一直什么都不显示..api是空的,我已经加了相关的注解和配置文&#x4EF6;
 
&mdash;

**Comment by zhangyc** [comment]
是作者大大啊,哈哈哈已经处理好了.shiro把所有没有配的请求都拦截了.我配置了一下就ok了
