### ISSUE TITLE
角色授权问题

### ISSUE THREAD

**Issue by 635399797** [wuyouzhuguli/FEBS-Shiro#78]
在角色管理中对角色进行授权时，正常应该选择子菜单后会自动选中父菜单，现在并没有递归选中，造成如果授权时只选中子菜单没选中父菜单的话，该角色登录后没有显示菜单的情况。

**Comment by wuyouzhuguli** [comment]
树形组件父子联动关了，比如角色A只有某个菜单的查看权限，如果树形组件联动不关闭的话，当你编辑该角色的时候，选中这个菜单，它下面的按钮也都会被选中；如果所有按钮取消勾选，父菜单也会被取消选中。

**Comment by 635399797** [comment]
是否可以改为选中父菜单的时候不会选中子菜单，但是选中子菜单的话会关联选中父菜单，就不会造成你说的问题了

**Comment by wuyouzhuguli** [comment]
受限于树形组件，找了挺多基于LayUI的树形组件，只有目前这个无论是UI还是API，都能算上比较满意了..

**Comment by 635399797** [comment]
好的。
如果我个人项目中想把父子联动开启的话应该修改哪个地方呢，请大佬给予指点

**Comment by wuyouzhuguli** [comment]
https://layuiextend.hsianglee.cn/eletree/ 查看它的文档。

如果不满意这个树形组件，只能修改它的源码或者替换别的了，但无论哪种方案总免不了折腾。

**Comment by 635399797** [comment]
收到，感谢
