### ISSUE TITLE
没有生成前段代码

### ISSUE THREAD

**Issue by playerlwq** [wuyouzhuguli/FEBS-Shiro#79]
没有生成前段代码没有生成前段代码没有生成前段代码没有生成前段代码

**Comment by wuyouzhuguli** [comment]
前端页面共性不强，不好抽出模板；多写点前端代码不是什么坏事。

**Comment by playerlwq** [comment]
好的，了解。谢谢大哥了------------------ 原始邮件 ------------------
发件人: "mrbird"<notifications@github.com>
发送时间: 2019年6月27日(星期四) 晚上11:59
收件人: "wuyouzhuguli/FEBS-Shiro"<FEBS-Shiro@noreply.github.com>;
抄送: "playerlwq"<2395499549@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wuyouzhuguli/FEBS-Shiro] 没有生成前段代码 (#79)



前端页面共性不强，不好抽出模板；多写点前端代码不是什么坏事。
 
&mdash;
