### ISSUE TITLE
项目部署完毕启动遇到数据源无法注入的问题

### ISSUE THREAD

**Issue by 1175687609** [wuyouzhuguli/FEBS-Shiro#83]
### 问题描述
redis 数据库，mysql 安装完成
启动项目报错
### 复现步骤
简单描述下问题复现的步骤

### 相关截图

![image](https://user-images.githubusercontent.com/35195325/61195865-892ee780-a6fd-11e9-9fdc-afc9f8995294.png)
![image](https://user-images.githubusercontent.com/35195325/61195892-b54a6880-a6fd-11e9-87c4-72cdb210cfb7.png)

> issue模板，by MrBird.

**Comment by BigBearGitHub** [comment]
warn是警告不是错误吧

**Comment by wuyouzhuguli** [comment]
中间表没有主键，Mybatis Plus报的警告，忽略即可

**Comment by 1175687609** [comment]
已解决谢谢





在 2019-07-15 13:41:20，"mrbird" <notifications@github.com> 写道：


中间表没有主键，Mybatis Plus报的警告，忽略即可
