### ISSUE TITLE
能否嵌入远程页面

### ISSUE THREAD

**Issue by shf4715** [wuyouzhuguli/FEBS-Shiro#85]
### 问题描述
需要将权限系统完全独立作为多个系统的通用入口，点击菜单展示远程内容，请问现在的系统能否做到。

### 复现步骤
无

### 相关截图
无

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
@shf4715 可以


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by wuyouzhuguli** [comment]
可以用iframe
