### ISSUE TITLE
shiroRealm service循环依赖

### ISSUE THREAD

**Issue by Hatsuhikari** [wuyouzhuguli/FEBS-Shiro#87]
### 问题描述
 Bean with name 'roleServiceImpl' has been injected into other beans [shiroRealm] in its raw version as part of a circular reference, but has eventually been wrapped. This means that said other beans do not use the final version of the bean. This is often the result of over-eager type matching - consider using 'getBeanNamesOfType' with the 'allowEagerInit' flag turned off, for example

### 复现步骤
启动

**Comment by wuyouzhuguli** [comment]
异常信息过少，没办法判断问题所在。

**Comment by wuyouzhuguli** [comment]
过久没有回复，自动关闭。
