### ISSUE TITLE
新增菜单时直接回车会插入两条数据

### ISSUE THREAD

**Issue by hzeddielau** [wuyouzhuguli/FEBS-Shiro#89]
### 问题描述
在菜单管理中，新增菜单时直接回车会插入两条数据

### 复现步骤
打开“菜单管理”，选择”新增菜单“，输入菜单名称后直接回车

### 相关截图

![WX20190810-102430](https://user-images.githubusercontent.com/34993453/62816396-4247dc80-bb59-11e9-94f0-f507fe1f33e4.png)

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
感谢指出，已修复
