### ISSUE TITLE
请问作者：菜单管理里面的按钮类型作用是什么？

### ISSUE THREAD

**Issue by icechen1219** [wuyouzhuguli/FEBS-Shiro#95]
### 问题描述
菜单管理里面可以在二级菜单下面增加按钮，并设置权限。但是实在找不到在什么地方对接？二级菜单子页面的增删改按钮，是通过如下代码明文创建的：
<div class="dropdown actions__item" shiro:hasAnyPermissions="menu:add,menu:delete,menu:update">
                        <i data-toggle="dropdown" class="zmdi zmdi-more-vert"></i>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a href="javascript:void(0)" class="dropdown-item" data-toggle="modal" data-target="#menu-add" shiro:hasPermission="menu:add">新增</a>
                            <a href="javascript:void(0)" class="dropdown-item" onclick="updateMenu()" shiro:hasPermission="menu:update">修改</a>
                            <a href="javascript:void(0)" class="dropdown-item" onclick="deleteMenus()" shiro:hasPermission="menu:delete">删除</a>
                        </div>
                    </div>

### 复现步骤
作者的整体工程结构非常清晰，比较适合二次开发。所以特别希望作者解惑。这个按钮到底是解决系统的哪一部分功能？十分感谢！

### 相关截图

  | 3 | 用户管理 |   | 菜单 | user | user:list | 2017-12-27 16:47:13
-- | -- | -- | -- | -- | -- | -- | --
  | 11 | 新增用户 |   | 按钮 |   | user:add | 2017-12-27 17:02:58
  | 12 | 修改用户 |   | 按钮 |   | user:update | 2017-12-27 17:04:07
  | 13 | 删除用户 |   | 按钮 |   | user:delete | 2017-12-27 17:04:58

**Comment by wuyouzhuguli** [comment]
对应用户模块增删改方法的权限：[link](https://github.com/wuyouzhuguli/FEBS-Shiro/blob/v2.0/src/main/java/cc/mrbird/febs/system/controller/UserController.java)。

**Comment by icechen1219** [comment]
> 对应用户模块增删改方法的权限：[link](https://github.com/wuyouzhuguli/FEBS-Shiro/blob/v2.0/src/main/java/cc/mrbird/febs/system/controller/UserController.java)。

感谢作者！我大致明白了。我的理解是这样的：网页和接口上的权限标识，是说明只能具备这个权限的人可以访问它们，但是登录用户是否具备权限，需要靠菜单/按钮管理来指定。不知道理解的正确不，请作者斧正。再次感谢！

**Comment by wuyouzhuguli** [comment]
@icechen1219 是的，就是这个意思


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by icechen1219** [comment]
再次感谢作者。关闭issue了。
