### ISSUE TITLE
代码生成遇到的问题

### ISSUE THREAD

**Issue by gelibo** [wuyouzhuguli/FEBS-Shiro#96]
### 问题描述
1、生成代码丢失字符
2、实体中double类型字段未生成

### 复现步骤
1、生成配置中，是否去除表前缀 选择是。

### 相关截图
![image](https://user-images.githubusercontent.com/14520562/63906138-5476b580-ca49-11e9-8eec-00906786ad3f.png)

如果表名中的中间字符正好有t_，比如 t_aaat_bbb ,那么生成的实体为 AaaBbb。t_被替换成空。
解决方式：
![image](https://user-images.githubusercontent.com/14520562/63906203-9b64ab00-ca49-11e9-898f-52077e53919a.png)

2、表字段中有double类型时，entity.ftl 模板文件中应追加

    <#if column.type = 'double'>
    private Double ${column.field?uncap_first};

    </#if>

**Comment by wuyouzhuguli** [comment]
感谢指出，会找个时间修复，或者劳烦您提个PR😛

**Comment by gelibo** [comment]
PR 已提交。

**Comment by wuyouzhuguli** [comment]
感谢，已将您添加到贡献者列表。
