### ISSUE TITLE
这个系统是前后分离的吗？

### ISSUE THREAD

**Issue by zJohny** [wuyouzhuguli/FEBS-Shiro#99]
### 问题描述
简单描述下遇到的问题

### 复现步骤
简单描述下问题复现的步骤

### 相关截图
提供相关截图，以协助问题分析

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
不是，前后端分离可以参考FEBS Vue

**Comment by zJohny** [comment]
收到，非常感谢您



---原始邮件---
发件人: "mrbird"<notifications@github.com&gt;
发送时间: 2019年9月4日(星期三) 下午5:01
收件人: "wuyouzhuguli/FEBS-Shiro"<FEBS-Shiro@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"zJohny"<2312006169@qq.com&gt;;
主题: Re: [wuyouzhuguli/FEBS-Shiro] 这个系统是前后分离的吗？ (#99)



不是，前后端分离可以参考FEBS Vue
